export const SECTION_TYPE_MAP = {
  personalDetails: 'personal',
  education: 'education',
  experience: 'experience',
  referees: 'referees',
  publications: 'publications_journal',
  conferencePublications: 'publications_conference',
  booksPublications: 'publications_books',
  patents: 'patents',
  projects: 'sponsored_projects',
  consultancyProjects: 'consultancy_projects',
  phdSupervision: 'phd_supervision',
  subjectsTaught: 'subjects_taught',
  organizedPrograms: 'organized_programs',
  creditPoints: 'credit_points',
  otherInfo: 'other_info',
  documents: 'final_documents',
  declaration: 'declaration',
  photo: 'photo',
  signature: 'signature',
  custom: 'custom',
};

export const INITIAL_FORM_DATA = {
  personalDetails: {},
  education: [],
  experience: [],
  referees: [],
  publications: [],
  conferencePublications: [],
  booksPublications: [],
  patents: [],
  projects: [],
  consultancyProjects: [],
  phdSupervision: [],
  subjectsTaught: [],
  organizedPrograms: [],
  creditPoints: {},
  otherInfo: {},
  documents: {},
  declaration: {},
  photo: {},
  signature: {},
  custom: {},
};
